# Generated by Django 3.0.5 on 2020-06-13 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('limit', models.TextField(null=True)),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bs', to='test_app.A')),
            ],
        ),
    ]
